name: My First Deployment Workflow

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: checkout files
        uses: actions/checkout@v7.0.0
      - name: list files
        run: ls
      - name: show html code
        run: cat index.html
